version: "2"

services:
  consol:
    image: dorowu/ubuntu-desktop-lxde-vnc
    environment:
      VNC_RESOLUTION: 1360x768
      VNC_PW: 1
      VNC_COL_DEPTH: 32
      VNC_PASSWORD: 1
    volumes:
      - /dev/shm:/dev/shm
    restart: always
    shm_size: '256m'
    ports:
    - 80:80
