version: "2"

services:
  consol:
    image: consol/ubuntu-icewm-vnc
    environment:
      VNC_RESOLUTION: 1360x768
      VNC_PW: 1
      VNC_COL_DEPTH: 32
    restart: always
    shm_size: '256m'
    ports:
    - 6901:6901
